modLoader="javafml"
loaderVersion="[44,)"
license="MIT"
[[mods]]
modId="tinycoal"
version="${file.jarVersion}"
displayName="Example Mod"
logoFile="icon.png"
authors="AzureDoom"
description='''
Allows you to convert coal or charcoal to Tiny Coal/Charcoal.
'''
[[dependencies.multiloader]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.multiloader]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"

