modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="tinycoal"
version="${file.jarVersion}"
displayName="Tiny Coal"
logoFile="icon.png"
authors="AzureDoom"
description='''
Allows you to convert coal or charcoal to Tiny Coal/Charcoal.
'''
[[dependencies.multiloader]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.multiloader]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

